# Generated by Django 4.2.5 on 2023-09-30 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_expense_expenseshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseshare',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to='split.expense'),
        ),
        migrations.AlterField(
            model_name='expenseshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
